### ISSUE TITLE
[Vote] 데모데이 투표화면 API 연결

### ISSUE THREAD

**Issue by flowersayo** [TherapEase-CEOS/react-vote-17th#14]
## Description
데모데이 투표 기능을 완성합니다.

## Todo
- [x] 데모데이 서비스 조회
- [x] 데모데이 서비스 투표
- [x] 데모데이 결과 조회
