### ISSUE TITLE
[Vote] API Mock Server 구축 (json-server)

### ISSUE THREAD

**Issue by flowersayo** [TherapEase-CEOS/react-vote-17th#15]
## Todo
- [x] axios 모듈생성
- [ ] json-server 구축 
    - [x] 데모 서비스 목록 조회 
    - [x] #16
    - [ ] 데모 서비스 결과 조회 

## ETC

- 폴더 구조

└─ db.json  ← API mock 서버에 띄우기 위한 데이터
└─ src/
      ├─ components/
      ├─ services/    ← axios 모듈 관리 폴더
      │   └─ authService.js   ← 로그인, 회원가입, 로그아웃 등 유저 인증 관련
      │   └─ voteService.js ← 투표 조회, 투표, 투표결과 조회 관련
      ├─ utils/
      │   └─ http.js <= 커스텀 axios 모듈
      └─ App.js
      
 # 전달사항
 
1.  Config.js 에 export const API_SERVER_BASE_URL = 'http://localhost:8000'; 상수 추가
2. 토큰 저장은 우선 로컬 스토리지에 access_token 라는 이름으로 해두도록 했는데 수정할 일 있으면 utils/HTTP.tsx에서 바꿔줘!!
    const token = localStorage.getItem('access_token');
3. json-server --watch db.json --port 8000 로  localhost:8000 에서 api mock server 실행
4. src/interface/interface.tsx 추가
