### ISSUE TITLE
[Vote] 파트장 투표 화면 UI 구현

### ISSUE THREAD

**Issue by Gaeun-Kwon** [TherapEase-CEOS/react-vote-17th#3]
## Description
파트장 투표 화면 UI 를 구현합니다.
[피그마 참고](https://www.figma.com/file/7xoPYTjMHcwPk2yl92Eynx/%ED%98%91%EB%8F%99%EA%B3%BC%EC%A0%9C-%EB%A0%88%ED%8D%BC%EB%9F%B0%EC%8A%A4?type=design&node-id=0-1&t=AVKfGeGFlviekOha-0)

![image](https://github.com/TherapEase-CEOS/react-vote-17th/assets/65700066/d738544f-839b-4ade-86a9-72a0121ce8f2)

## Todo
- [x] 파트장 투표 진입 화면 UI
- [x] 파트장 투표창 화면 UI
- [x] 파트장 투표 결과 화면 UI
