### ISSUE TITLE
[Vote] 데모데이 투표화면 UI

### ISSUE THREAD

**Issue by flowersayo** [TherapEase-CEOS/react-vote-17th#4]
## Description
데모데이 투표 화면 레이아웃 UI 를 구성합니다.

## Todo

- [x] 데모 메인 화면
- [x] 데모 투표 화면
- [x] 데모 결과 화면
