### ISSUE TITLE
[Vote] 메인 투표화면 설계

### ISSUE THREAD

**Issue by flowersayo** [TherapEase-CEOS/react-vote-17th#5]
## Description
기초 레이아웃 및 투표화면에 필요한 기본 컴포넌트들을 생성합니다.

## Todo
- [x] 초기 라우팅 설계
- [x] 투표 메인 화면 UI
- [x] 폰트 ( Typography )
- [x] 헤더
- [x] 공통 컴포넌트 개발 (메인버튼, 셀렉트박스버튼)
